/**
 * Turns the brand package into the things the app actually ships: a
 * TypeScript module of SVG sources, and the app icon as SVG.
 *
 * The SVGs go into the bundle as strings, not into `public`, because every
 * one of them is drawn onto the canvas: a `data:` URI keeps `toDataURL`
 * working, and a file URL would be one more thing that can 404 mid-export.
 *
 * Run it after the package changes:
 *   node scripts/build-brand.mjs
 * then the PNG icons, which need a browser to rasterise:
 *   node scripts/build-icons.mjs
 */

import fs from 'node:fs'
import path from 'node:path'

const PKG = 'assets/brand/mab'
const read = (p) => fs.readFileSync(path.join(PKG, p), 'utf8')
const tokens = JSON.parse(read('design-tokens.json'))

/** every SVG we ship must carry width and height, or Safari draws nothing */
function checked(name, svg) {
  if (!/^<svg[^>]*\swidth="\d/.test(svg) || !/^<svg[^>]*\sheight="\d/.test(svg)) {
    throw new Error(`${name}: the root <svg> needs explicit width and height`)
  }
  if (/<image|xlink:href|url\(http|<script|@font-face|font-family/.test(svg)) {
    throw new Error(`${name}: external reference or live font found`)
  }
  return svg.replace(/\n\s*/g, '').trim()
}

const stamp = checked('stamp', read('watermarks/mab-stamp-white.svg'))
const [sw, sh] = tokens.watermark.stampSize
if (!stamp.includes(`viewBox="0 0 ${sw} ${sh}"`)) throw new Error(`stamp: expected a ${sw} x ${sh} box`)

const out = `/**
 * Brand assets as SVG source, generated by scripts/build-brand.mjs from
 * assets/brand/mab. Do not edit by hand: edit the package.
 *
 * They are strings rather than files under public/ because each one is drawn
 * onto the canvas through a \`data:\` URI, which keeps the canvas untainted and
 * \`toDataURL\` working - the same reason this project has no CDN fonts.
 */

/** one МАБ mark, white, centred in a ${sw} x ${sh} box; opacity left to the caller */
export const STAMP_SVG = ${JSON.stringify(stamp)}

/** the pyramid alone, in the brand's blue and white */
export const SIGN_SVG = ${JSON.stringify(checked('sign', read('logos/mab-sign.svg')))}

/** the pyramid and «МАБ» in a row, white type */
export const LOGO_HORIZONTAL_SVG = ${JSON.stringify(checked('horizontal', read('logos/mab-horizontal-white.svg')))}

/** the artboard the watermark coordinates are written in */
export const WATERMARK_ARTBOARD = {
  cloth: { x: ${tokens.watermark.cloth[0]}, y: ${tokens.watermark.cloth[1]}, w: ${tokens.watermark.cloth[2]}, h: ${tokens.watermark.cloth[3]} },
  columns: ${tokens.watermark.columns},
  stampW: ${sw},
  stampH: ${sh},
} as const

/**
 * The indicator's own artboard, 140 x 88 = one eighth of the cloth. The plate
 * itself is drawn in Konva so it carries the same light and materials as the
 * rest of the table.
 */
export const POWER_ARTBOARD = { w: ${tokens.indicator.width}, h: ${tokens.indicator.height} } as const

export const BRAND = {
  blue: '${tokens.colors.blue}',
  navy: '${tokens.colors.navy}',
  cream: '${tokens.colors.cream}',
  white: '${tokens.colors.white}',
  tile: '${tokens.colors.tile}',
} as const
`
fs.mkdirSync('src/brand', { recursive: true })
fs.writeFileSync('src/brand/assets.ts', out)

// the app icon: the pyramid on a dark tile, the way the logo is meant to be
// seen, so it reads on a light tab bar too
const sign = read('logos/mab-sign.svg')
const vb = /viewBox="([^"]+)"/.exec(sign)[1].split(/\s+/).map(Number)
const shapes = sign.slice(sign.indexOf('</title>') + 8, sign.lastIndexOf('</svg>'))
// the pyramid fills 74% of the tile: clear of the rounded corners, and still
// the largest thing a 16 px favicon can show
const fill = 128 * 0.74
const k = fill / vb[2]
const off = (128 - fill) / 2
fs.mkdirSync('public/brand', { recursive: true })
fs.writeFileSync(
  'public/brand/icon.svg',
  `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">` +
    `<rect width="128" height="128" rx="26" fill="${tokens.colors.tile}"/>` +
    `<g transform="translate(${(off - vb[0] * k).toFixed(3)} ${(off - vb[1] * k).toFixed(3)}) scale(${k.toFixed(5)})">${shapes}</g></svg>\n`,
)

fs.mkdirSync('public/fonts', { recursive: true })
fs.copyFileSync(path.join(PKG, 'fonts/Manrope-variable.woff2'), 'public/fonts/manrope.woff2')
fs.copyFileSync(path.join(PKG, 'fonts/OFL.txt'), 'public/fonts/LICENSE-Manrope.txt')

const kb = (s) => Math.round(s.length / 102.4) / 10
console.log(`src/brand/assets.ts written: stamp ${kb(stamp)} KB, logo ${kb(read('logos/mab-horizontal-white.svg'))} KB`)
console.log('public/brand/icon.svg, public/fonts/manrope.woff2, LICENSE-Manrope.txt written')
